### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by idgserpro** [plone/plone.mocktestcase#1]
If I use plone.mocktestcase with layer of plone.app.testing, I get this error:

``` bash
Traceback (most recent call last):
  File "./bin/test", line 320, in <module>
    '--test-path', '/home/user/sites/my.product/src',
  File "/home/user/cache-python/eggs/zope.testing-3.9.7-py2.7.egg/zope/testing/testrunner/__init__.py", line 35, in run
    failed = run_internal(defaults, args, script_parts=script_parts)
  File "/home/user/cache-python/eggs/zope.testing-3.9.7-py2.7.egg/zope/testing/testrunner/__init__.py", line 48, in run_internal
    runner.run()
  File "/home/user/cache-python/eggs/zope.testing-3.9.7-py2.7.egg/zope/testing/testrunner/runner.py", line 138, in run
    self.run_tests()
  File "/home/user/cache-python/eggs/zope.testing-3.9.7-py2.7.egg/zope/testing/testrunner/runner.py", line 242, in run_tests
    tear_down_unneeded(self.options, (), setup_layers, True)
  File "/home/user/cache-python/eggs/zope.testing-3.9.7-py2.7.egg/zope/testing/testrunner/runner.py", line 605, in tear_down_unneeded
    l.tearDown()
  File "/home/user/cache-python/eggs/plone.app.testing-4.2.5-py2.7.egg/plone/app/testing/helpers.py", line 371, in tearDown
    popGlobalRegistry(portal)
  File "/home/user/cache-python/eggs/plone.app.testing-4.2.5-py2.7.egg/plone/app/testing/helpers.py", line 193, in popGlobalRegistry
    previous = zca.popGlobalRegistry()
  File "/home/user/cache-python/eggs/plone.testing-4.0.15-py2.7.egg/plone/testing/zca.py", line 126, in popGlobalRegistry
    previous = current.__bases__[0]
IndexError: tuple index out of range
```

My test:

``` python
from my.product.testing import INTEGRATION_TESTING
from plone.mocktestcase.testcase import MockTestCase


class VocabulariesTestCase(MockTestCase):

    layer = INTEGRATION_TESTING

    def setUp(self):
        self.portal = self.layer['portal']

    def test_vocabulary(self):
        pass
```

**Comment by idgserpro** [comment]
The problem is caused by the call [zope.component.testing.tearDown](https://github.com/plone/plone.mocktestcase/blob/master/plone/mocktestcase/testcase.py#L19)
in the method [tearDown](https://github.com/plone/plone.mocktestcase/blob/master/plone/mocktestcase/testcase.py#L17)
@optilude  why that this method is called?
